// <auto-generated />
using System;
using Glviangle.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Glviangle.Data.Migrations
{
    [DbContext(typeof(GlviangleDBContext))]
    partial class GlviangleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Glviangle.Data.EF.Entities.Sample", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Key");

                    b.ToTable("Sample");
                });

            modelBuilder.Entity("Glviangle.Data.Entities.Admin.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = "Cate01",
                            Alias = "benh-vien",
                            CategoryName = "Bệnh viện"
                        },
                        new
                        {
                            Id = "Cate02",
                            Alias = "kham-pha",
                            CategoryName = "Khám phá"
                        },
                        new
                        {
                            Id = "Cate03",
                            Alias = "dich-vu",
                            CategoryName = "Dịch vụ"
                        },
                        new
                        {
                            Id = "Cate04",
                            Alias = "len-ke-hoach",
                            CategoryName = "Lên kế hoạch"
                        });
                });

            modelBuilder.Entity("Glviangle.Data.Entities.Admin.ChildCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategoryParentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryParentId");

                    b.ToTable("CategoryChild");

                    b.HasData(
                        new
                        {
                            Id = "CCate01",
                            Alias = "dien-thoai-samsung",
                            CategoryName = "Điện thoại Samsung",
                            CategoryParentId = "Cate01"
                        });
                });

            modelBuilder.Entity("Glviangle.Data.Entities.Client.Promotion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Promotion");

                    b.HasData(
                        new
                        {
                            Id = "PRO04",
                            DateFrom = new DateTime(2021, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2021, 6, 19, 12, 11, 21, 746, DateTimeKind.Local).AddTicks(1291),
                            Description = "Alo 1234",
                            Place = "Bệnh viện Bình Dân",
                            Thumbnail = "https://gleneagles.azureedge.net/images/default-source/community/lung-cancer_event-banner-01-(1).tmb-event.jpg?sfvrsn=73d05bfe_1",
                            Title = "Lung Cancer Screening Package"
                        });
                });

            modelBuilder.Entity("Glviangle.Data.Entities.Admin.ChildCategory", b =>
                {
                    b.HasOne("Glviangle.Data.Entities.Admin.Category", "category")
                        .WithMany("listChildCategory")
                        .HasForeignKey("CategoryParentId");

                    b.Navigation("category");
                });

            modelBuilder.Entity("Glviangle.Data.Entities.Admin.Category", b =>
                {
                    b.Navigation("listChildCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
